import turtle
turtle.speed("fastest")
def draw_levi(d, length):
	if d == 0:
		turtle.left(60)
		turtle.forward(length)
		turtle.right(120)
		turtle.forward(length)
		turtle.right(120)
		turtle.forward(length)
	else:
		turtle.left(60)
		turtle.forward(length / 2)
		turtle.right(120)
		turtle.forward(length / 2)
		turtle.left(120)
		turtle.forward(length / 2)
		turtle.left(120)
		turtle.forward(length / 2)
		turtle.right(120)
		turtle.forward(length / 2)
		turtle.right(120)
		turtle.forward(length / 2)
		turtle.forward(length / 2)
		turtle.right(120)
		turtle.forward(length / 2)
		turtle.forward(length / 2)
draw_levi(4, 200)
input()
